[package]
name = "staking_backend"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
solana-sdk = "1.18.15"
solana-client = "1.18.15"
bs58 = "0.5.1"
dotenv = "0.15.0"
